// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx1PviR9m6olDQ3yVYpWQc7u2x9FbAP1k',
    appId: '1:664327874488:web:9391aec51102c780a6d14d',
    messagingSenderId: '664327874488',
    projectId: 'weeklygacha-24683',
    authDomain: 'weeklygacha-24683.firebaseapp.com',
    storageBucket: 'weeklygacha-24683.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1PviR9m6olDQ3yVYpWQc7u2x9FbAP1k',
    appId: '1:664327874488:android:46edfb16f2ce799ca6d14d',
    messagingSenderId: '664327874488',
    projectId: 'weeklygacha-24683',
    storageBucket: 'weeklygacha-24683.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1PviR9m6olDQ3yVYpWQc7u2x9FbAP1k',
    appId: '1:664327874488:ios:YOUR_IOS_APP_ID', // 임시 값
    messagingSenderId: '664327874488',
    projectId: 'weeklygacha-24683',
    storageBucket: 'weeklygacha-24683.firebasestorage.app',
    iosBundleId: 'com.mycompany.weeklygacha',
  );
}
